### ISSUE TITLE
Support for aggregation funcs?

### ISSUE THREAD

**Issue by cktang88** [Ff00ff/mammoth#135]
Does this support aggregation funcs like `count`, `sum`, `array_agg`, `string_agg`, etc. ?

**Comment by martijndeh** [comment]
Yes, there is support for count, sum, min, max. avg, e.g.

```
db.select(count()).from(db.foo); // SELECT COUNT(*) FROM foo
```

`array_agg`, `string_agg`, etc are not supported yet. This should be very easy to add. Looking at the docs I think this lists the aggregate functions Mammoth should support. https://www.postgresql.org/docs/12/functions-aggregate.html

Is this something you would like to add?

**Comment by martijndeh** [comment]
I'll pick this one up. I hope you don't mind.

**Comment by martijndeh** [comment]
I added support for general-purpose aggregate functions e.g.:

```ts
db.select(arrayAgg(db.foo.name)).from(db.foo)
```
becomes
```sql
SELECT array_agg(foo.name) FROM foo;
```
returns type
```ts
{ arrayAgg: string[] }[]
```
