### ISSUE TITLE
Tool to check that the Mammoth schema matches the Postgres schema.

### ISSUE THREAD

**Issue by cakoose** [Ff00ff/mammoth#144]
In my test suite, I'd like to run something that verifies that my Postgres schema is compatible with what the structure I've defined for Mammoth.  Is there an easy way to do this already?

If not, I think I could probably figure out how to write it.  But it seems like a generally useful tool and maybe should be part of Mammoth itself, maybe in a sibling package?

**Comment by martijndeh** [comment]
To make sure your defined tables actually match your database schema, you can use the mammoth-cli. This is currently in the making at https://github.com/Ff00ff/mammoth-cli/tree/postgres-data-language-simulator. Soon there should be a beta release.

There is an initial documentation page explaining the flow which is available at https://mammoth.tools/migrations.

**Comment by cakoose** [comment]
Thanks!

(BTW, I'd suggest linking to https://mammoth.tools in the GitHub README.  Even though it's incomplete, there's still some useful stuff there.)

**Comment by martijndeh** [comment]
Good suggestion, will do!
