### ISSUE TITLE
Question: best way to define a concise type for the Mammoth DB object?

### ISSUE THREAD

**Issue by cakoose** [Ff00ff/mammoth#145]
I want to create a type alias for the DB object so that I can use it in function signatures.  For example, I have a wrapper around my controller functions that takes care of fetching the DB connection and managing the DB transaction, e.g.

```
async function wrapHandlerAsync<T>(handlerAsync: (db: DbType, ...) => Promise<T>): Promise<T> {
    const client = globalPool.getClient();
    const db = ...;
    client.query("BEGIN");
    try {
        await handlerAsync(db);
    } finally {
        ...
    }
}
```

What's the best way to write `DbType` in the function signature?  What I'm doing now:

```
function createDb(client: pg.Client) {
    return defineDb({...}, async (query, parameters) => {...});
}

type Db = ReturnType<typeof CreateDb>;
```

One downside is that I'm relying on inference.  For types that cross module boundaries, I prefer to not rely on inference.  Is there a better way to do it?

**Comment by martijndeh** [comment]
This is also how I do it nowadays. As long as I export the inferred type close to the implementation (in your case createDb) I don't mind too much on the inference. Outside modules will have no idea how the type is constructed and can simply use `Db` which is great. Also, as long as you do not use the `Db` within your tables or query executor you will not get any circular reference issues (weak spot inference, right).

Mammoth may provide some type to facilitate this but not sure in what form yet. The most straightforward solution would be in the form of `Db<T>` where `T` would be your tables e.g. `Db<typeof tables>` but it has some downsides as well.
