### ISSUE TITLE
Support Postgres `bytea` type for binary data?

### ISSUE THREAD

**Issue by cakoose** [Ff00ff/mammoth#151]
Mammoth currently doesn't have a type corresponding to Postgres' `bytea` type for binary data.  Can it be added?

For my use case, it would be nice to be able to pass/receive `Buffer` or `Uint8Array` values.

**Comment by martijndeh** [comment]
I added the `bytea` data type. Its type is set to `Buffer`. I also added all the other missing built-in general-purpose data types listed on https://www.postgresql.org/docs/12/datatype.html.

To define a column using bytea you can write the following:

```ts
import { defineTable, bytea, uuid } from '@ff00ff/mammoth';

const foo = defineTable({
  id: uuid().primaryKey().default(`gen_random_uuid()`),
  value: bytea(),
});
```

If you have a custom data type you can always use `dataType()` to create your own type:

```ts
import { defineTable, dataType, uuid, timestampWithTimeZone } from '@ff00ff/mammoth';

const foo = defineTable({
  id: uuid().primaryKey().default(`gen_random_uuid()`),
  createDate: timestampWithTimeZone().notNull().default(`now()`),
  test: dataType<Uint8Array>(`myspecialtype`),
});
```
