### ISSUE TITLE
Support for ENUM?

### ISSUE THREAD

**Issue by cakoose** [Ff00ff/mammoth#161]
Is there a way to use Postgres `ENUM` fields with Mammoth v1.x?

The [v0.10.x docs](https://www.npmjs.com/package/@ff00ff/mammoth/v/0.10.0) have something called `EnumColumn`, but I can't see anything like that in the v1.x codebase.

**Comment by martijndeh** [comment]
Correct, this is not supported in the main branch right now. I'll get this back in.

As an alternative, you can use a text column but pass in your own type. This does not give you the database safety checks you get when you use a type, but it gives you the same safety checks in your application code. The downside of a postgres type is that you cannot remove a value (you can rename a value though).

The below creates a `test` column with a specific string union type.

```ts
export const test = defineTable({
  id: uuid().primaryKey().notNull().default('gen_random_uuid()'),
  test: text<'foo' | 'bar' | 'baz'>().notNull(),
});
```

**Comment by martijndeh** [comment]
This is supported again. You can use the `enumType(..)` data type to configure this. I'll go through mammoth-cli as well to support creating and altering types as well.

```
export const test = defineTable({
  id: uuid().primaryKey().notNull().default('gen_random_uuid()'),
  test: enumType('my_enum_type', ['A', 'B', 'C'] as const).notNull(),
});
```
