### ISSUE TITLE
Where can be called on select directly

### ISSUE THREAD

**Issue by AuspeXeu** [Ff00ff/mammoth#170]
The following code will compile without errors.

`db.select(db.users.id).where(db.users.id.eq(1)).from(db.users)`

but generate the invalid SQL.

`SELECT users.id WHERE users.id = $1 FROM users`

Leaving the user with.

`error: syntax error at or near "FROM"`

**Comment by martijndeh** [comment]
This is correct. Mammoth doesn't fully ensure the SQL you type is also correct—yet. See https://github.com/Ff00ff/mammoth/issues/128. This is actually considered a good first issue to pick up for developers new to the codebase.

I'm closing this in favour of the already open issue. Thanks for the report!
