### ISSUE TITLE
count() returns of type string?

### ISSUE THREAD

**Issue by AuspeXeu** [Ff00ff/mammoth#176]
When I select count like so

`const [{ count }] = await db.select(count()).from(db.users)`

The type of count is `string`. Bug or feature? :)

**Comment by martijndeh** [comment]
It's a feature! ;-) `pg` returns `string` for thing like `bigint` which `count()` returns. There is some documentation in their repository and also ways to change it if you really want. https://github.com/brianc/node-postgres/issues/2344
