### ISSUE TITLE
Helping detect when I forget to `await`?

### ISSUE THREAD

**Issue by cakoose** [Ff00ff/mammoth#181]
I frequently forget to `await` my Mammoth `.insertInto(...)` and `.update(...)` calls.  The code ends up running without an error but the DB actions never happen.

Normally, either TypeScript or WebStorm's static analysis will warn me about a missing `await`.  This doesn't seem to happen for those Mammoth calls, though, possibly because the return value isn't a simple `Promise`?

I'm looking into enabling the ESLint "@typescript-eslint/no-floating-promises" rule.  The problem is that rule requires running ESLint in "compute type information" mode, which seems to make ESLint 5x slower on our codebase.

I don't really have a recommendation here, but here are some ideas:
- Is there a way to detect this dynamically?  I wouldn't mind getting a runtime error at least.
- Is there a modification to Mammoth (e.g. some kind of annotation) that would cause WebStorm's static analysis to catch this case?  (Kind of a WebStorm-specific issue, so maybe I'll ask on their forums.)
- Maybe Mammoth can include an ESLint rule to detect this particular issue without needing to run ESLint in "compute type information" mode?

Maybe someone else has figured out another way to solve this problem?

**Comment by martijndeh** [comment]
I agree this is a real problem and it would be nice to have something to prevent this.

Just zooming in a bit on the static analysis about missing `await` by WebStorm/TypeScript you're claiming. What is it doing with the below snippet? For which of the three cases below does the warning work?

```ts
const main = async () => {
  const test = async (): Promise<number> => {
    return 123;
  };

  // 1. So this will give you a warning?
  test();

  // 2. This will not give you a warning?
  new TestClass1().go();

  // 3. And what about this one which explicitly implements PromiseLink?
  new TestClass2().go();
};
main();

class TestClass1 {
  go(): TestClass1 {
    return undefined as any;
  }

  then(
    onFulfilled?:
      | ((value: number) => any | PromiseLike<any>)
      | undefined
      | null,
    onRejected?: ((reason: any) => void | PromiseLike<void>) | undefined | null,
  ) {
    return 123;
  }
}
class TestClass2 implements PromiseLike<number> {
  go(): TestClass2 {
    return undefined as any;
  }

  then<TResult1 = number, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): PromiseLike<TResult1 | TResult2> {
    return 123 as any;
  }
}
```

**Comment by cakoose** [comment]
I get a warning for 1, and no warning for 2 or 3.

I also get the warning if I change `test` to return `PromiseLike` instead of `Promise`:

```
  const test = (): PromiseLike<number> => {
    throw new Error();
  };
```

I've filed a bug on the WebStorm issue tracker ([link](https://youtrack.jetbrains.com/issue/IDEA-256908)) now that I understand it a bit better.

**Comment by martijndeh** [comment]
Good.

I'll keep this open for a bit and do an experiment with creating an eslint plugin to lint this without requiring type information.

**Comment by cakoose** [comment]
BTW, I ended up enabling the "no-floating-promises" ESLint rule and it has been working fine.  It makes ESLint run much more slowly, but it seems tolerable at this point (our codebase is still relatively small).

So at least for us, the priority isn't that high anymore.

**Comment by martijndeh** [comment]
Great. That's good enough. I'll consider an eslint plugin out of scope for now and will close this issue.
