### ISSUE TITLE
Non-brittle way of determining pkey constraint violation?

### ISSUE THREAD

**Issue by cakoose** [Ff00ff/mammoth#185]
I sometimes attempt an insert, knowing that there's a chance it might fail, e.g.

```typescript
try {
    await db.insertInto(db.users).values({
        handle: ...,
        ...
    });
} catch (err) {
    if (err && err.severity === 'ERROR' && err.code === '23505' && err.constraint === 'users_pkey') {
        return {success: false, reason: 'user handle is already taken'};
    }
}
```

The problem is that specifying the table name as a string (`'users_pkey'`) is brittle.  We had a case where we updated the table name (via an IDE refactoring) but forgot to update the constraint string.

(A "user handle is already taken" error should obviously have a test.  But we also check for more rare pkey clashes and probably won't have test coverage for all of them.)

Can Mammoth help with this problem?  For example, one minimalist solution would be something like:

```
const pkeyConstraintName = `${mammoth.tableName(db.users)}_pkey`;
```

A less minimalist option:

```
const pkeyConstraintName = mammoth.pkeyName(db.users);
// `pkeyName` can be a bit smarter and adapt to Postgres' 63-char limit on identifier names.
```

**Comment by cakoose** [comment]
Oh whoops, looks like I misunderstood how Postgres indexes work.  Renaming a table doesn't auto-rename the pkey index.

The high-level problem is still the same -- I'd like a non-brittle way to check for constraint violations, and am wondering if Mammoth can help.  But my suggested solutions don't really make sense.

**Comment by martijndeh** [comment]
I think if you want to have a non-brittle way you should explicitly name the constraints yourself so you can check on those. I looked into the naming convention of constraints in postgres and I think it's difficult to determine the exact name of an implicitly named constraint (e.g. if you use columns in the constraint it sometimes takes those into the name as well, etc).

Apart from that, I wonder why you just don't always return `{ success: false }` when you hit a `code === '23505'` and _try_ to construct a reason based on the constraint. But if you cannot determine the appropriate reason you just fall back to an unknown reason and optionally warn so you're aware something is off.

What do you think?

**Comment by cakoose** [comment]
Yeah, this is probably a more involved feature than I originally thought.  But it might fit well with the idea of the Mammoth CLI checking consistency between the TS DB schema and the actual Postgres schema.  For example, maybe Mammoth allows you to specify constraints in TS as well?

```
const usersPkeyConstraint = defineConstraint(db.users, 'users_pkey', [db.users.handle]);
```

> Apart from that, I wonder why you just don't always return { success: false } when you hit a code === '23505' and try to construct a reason based on the constraint. But if you cannot determine the appropriate reason you just fall back to an unknown reason and optionally warn so you're aware something is off.

Ah yeah, my code snippet is incomplete; the catch block was missing a `throw`:

```
} catch (err) {
    if (err && err.severity === 'ERROR' && err.code === '23505' && err.constraint === 'users_pkey') {
        return {success: false, reason: 'user handle is already taken'};
    }
    throw err;
}
```

I should definitely not be swallowing the error.

**Comment by martijndeh** [comment]
Yes, totally agree, it's on the list to support indices and constraints as well.

> Ah yeah, my code snippet is incomplete; the catch block was missing a throw:
Yea I was assuming that, but what I mean is something like the below. Obviously I don't know your use cases.

```ts
} catch (err) {
    if (err && err.severity === 'ERROR' && err.code === '23505') {
        return {success: false, reason: err.constraint === 'users_pkey' ? 'user handle is already taken' : 'unknown constraint error'};
    }
    throw err;
}
```

**Comment by cakoose** [comment]
Oh, I see.

In my case I'm handling a "create user" HTTP API request.  Returning "unknown constraint error" gives more information than returning an HTTP 500, I don't think the client could do anything useful with that additional information.  I'd rather just log the exception on the server, associated with a request ID for later lookup.
