### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by pauldraper** [Ff00ff/mammoth#2]
This project is pre-1.0 and was last updated 2018-10-29.

1. Is the API stable and the implementation production-ready?
2. What future fixes/additions -- if any -- are planned?

**Comment by martijndeh** [comment]
I moved this project to a submodule of a project of mine (which is in production), but continued development, so a lot of changes are not pushed to this repo yet. I'll take some time to this week to move back to this public repo and publish to npm.

The philosophy of the public api is to stick as close as possible to PostgreSQL—to avoid any unnecessary abstractions. So, the api is fairly stable, as in it won't suddenly change, but there are still some sql commands not supported.

I'll keep this issue open until I updated the repo again. But feel free to ask any questions in the meantime.

**Comment by gilbert** [comment]
I'm also highly interested in this library. What kind of changes have you made?

**Comment by martijndeh** [comment]
OK, I just updated the repo. Let me know what you think.

As for the changes: some bugs are fixed and a lot of typing improvements e.g. when inserting specifying id is not required anymore. :) On delete and update cascade/restrict/no action/set null/set default and a handful more sql keywords are supported now.

**Comment by ansarizafar** [comment]
@martijndeh  Any update on project status? I would love to use mammoth in my new project.

**Comment by martijndeh** [comment]
I'm not working on a project which uses postgres and typescript right now, so new development is paused currently. I think it needs some dependency updates and check with the latest typescript again. Still, I think Mammoth is feature-complete enough to be usable, especially because I value the type safety so much. But yea officially the status is still pre-production.
