### ISSUE TITLE
Get query as a string

### ISSUE THREAD

**Issue by cakoose** [Ff00ff/mammoth#210]
I'm building most of my queries with Mammoth.

There are some cases where I want to do this:

```sql
WITH inner AS (...)
SELECT count(*) FROM inner
```

Mammoth can't do "WITH ..." yet, so I'm writing it with raw SQL.  However, the "..." is something I can do with Mammoth, and in fact, I'm already doing it somewhere else.

What would be nice: If that Mammoth object had a ".toSql()` function, I could use that to create the "..." instead of writing it in raw SQL, then plug it in to the bigger "WITH ..." expression.

**What would `.toSql()`** return?

It would have to return the query and the values in some format.  Returning the query as a single string with `$1`/`$2` placeholders would be problematic because they're referencing absolute positions.  What might work: something similar to JavaScript's custom template literals, e.g. an `Array<string>` for the query and an `Array<unknown>` for the values.

**Comment by martijndeh** [comment]
I agree it makes sense to expose something so you can get the raw sql back. I'll work on this.

Internally there is `createQueryState()` which needs the query's tokens. This is an internal representation which we probably shouldn't expose to the outside world.

> Mammoth can't do "WITH ..." yet, so I'm writing it with raw SQL. However, the "..." is something I can do with Mammoth, and in fact, I'm already doing it somewhere else.

Actually... there is support for WITH. ;) You can even do multiple statements.

```ts
const query = db.with(
      `regionalSales`,
      () =>
        db
          .select(db.orderLog.region, sum(db.orderLog.amount).as(`totalSales`))
          .from(db.orderLog)
          .groupBy(db.orderLog.region),
      `topRegions`,
      ({ regionalSales }) =>
        db
          .select(regionalSales.region)
          .from(regionalSales)
          .where(
            regionalSales.totalSales.gt(
              db.select(sum(regionalSales.totalSales).divide(10)).from(regionalSales),
            ),
          ),
      ({ topRegions }) =>
        db
          .select(
            db.orderLog.region,
            db.orderLog.product,
            sum(db.orderLog.quantity).as(`productUnits`),
            sum(db.orderLog.amount).as(`productSales`),
          )
          .from(db.orderLog)
          .where(db.orderLog.region.in(db.select(topRegions.region).from(topRegions)))
          .groupBy(db.orderLog.region, db.orderLog.product),
    );
```

**Comment by martijndeh** [comment]
You can now get the sql from any query by calling `toSql(query)`. `toSql()` should be an escape hatch and is therefore not an instance method on the query directly (e.g. `query.toSql()`) so it doesn't pollute the public api.

This change just hit master and will be in a next release soon enough.
