### ISSUE TITLE
Idea: replace length-specific overloads with TS 4.0 variadic tuple types

### ISSUE THREAD

**Issue by cakoose** [Ff00ff/mammoth#219]
TypeScript 4.0 added [variadic tuple types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#variadic-tuple-types).

Mammoth's variable-length methods like `.select(...)` are currently implemented with one signature overload for each length of arguments, from 1-75.  Can/should that be replaced with variadic tuple types?

Potential advantages:
1. My IDE occasionally freezes for ~3 seconds when trying to show the autocomplete for methods like `.select(...)`.  I wonder if that's because of the number of length-specific overloads.
2. I wonder if things like this will be easier: <https://github.com/Ff00ff/mammoth/issues/218>.  (I don't actually know...)
3. Potentially better type error messages.

**Comment by cakoose** [comment]
I tried cobbling something together but couldn't get it working.  This is how far I got:

```ts
export interface SelectFnNew {
  <Columns extends Array<Selectable>>(
    ...columns: [...Columns]
  ): SelectQuery<
    TupleToIntersection<GetSelectables<Columns>>,
    ContainsStar<Columns[number]>>;
}

type GetSelectables<Columns extends Array<any>> = {[I in keyof Columns]: Columns[I] extends Selectable ? GetSelectable<Columns[I]> : never}

// Taken from https://stackoverflow.com/a/51604379/163832
type BoxedTupleTypes<T extends any[]> = {[P in keyof T]: [T[P]]}[Exclude<keyof T, keyof any[]>]
type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends ((k: infer I) => void) ? I : never;
type UnboxIntersection<T> = T extends { 0: infer U } ? U : never;
type TupleToIntersection<T extends Array<any>> = UnboxIntersection<UnionToIntersection<BoxedTupleTypes<T>>>
```

**Comment by martijndeh** [comment]
Nice work. I think if you add something like `type ToColumns<T> = T extends { [column: string]: any } ? T : never;` and wrap that around the location where you see the error it should be result (and types should still work).

**Comment by martijndeh** [comment]
@cakoose I have some time the comings weeks to make some improvements. If you don't mind I'm going to take your work and replace those length-specific overloads. Do let me know if you're planning to create a pull request yourself, then I'll hold off on this one.

**Comment by cakoose** [comment]
Go for it!  (If I get another chance to look at this, I'll update this issue.)

**Comment by martijndeh** [comment]
Thanks, this is fixed now. I'll try to apply this technique to the other many signature overloads like `returning()`.
