### ISSUE TITLE
Bug: leftJoin produces the wrong SQL

### ISSUE THREAD

**Issue by echentw** [Ff00ff/mammoth#236]
Here's the source code:
https://github.com/Ff00ff/mammoth/blob/144b46482608f9c1582f33832e234e2b6dfda2fc/src/select.ts#L230-L237

Looks like `leftJoin` produces an `INNER JOIN`. The correct thing should be a `LEFT JOIN`, right?

**Comment by martijndeh** [comment]
Thanks this was just merged.

**Comment by martijndeh** [comment]
This is also released in 1.3 now.
