### ISSUE TITLE
Table insert: Support calling functions

### ISSUE THREAD

**Issue by cakoose** [Ff00ff/mammoth#245]
I'm using Postgres to store a bunch of geographic regions, e.g.:

```ts
CREATE TABLE regions (
    name string,
    latlong_shape geography
);
```

I'm loading data into the table from a "geojson" file.  Postgres has support for that format:

```ts
INSERT INTO regions (name, latlong_shape)
VALUES ('California', ST_GeomFromGeoJSON('{"type": "Polygon", "coordinates": [...]}'))
```

Assuming I can hack up a Mammoth `Expression` helper for `ST_GeomFromGeoJSON`, can I write that INSERT with Mammoth?  Something like:

```ts
db.insertInto(db.regions).values({
    name: ...,
    latlongShape: stGeomFromGeoJSON(...),
});
```

**Comment by martijndeh** [comment]
This is now supported. It just hit master and will be available in the next release. You can do something like:

```ts
db.insertInto(db.foo).values({
  name: raw<string>`get_some_text()`,
});
```

You can also use queries.

```ts
db.insertInto(db.foo).values({
  name: db.select(db.foo.name.concat(` 2`)).from(db.foo).limit(1),
});
```
