### ISSUE TITLE
creating tables?

### ISSUE THREAD

**Issue by Yaikava** [Ff00ff/mammoth#269]
Is there a way to create tables?
(Creating them in the database.
Equivalent to running something like this manually
```sql
CREATE TABLE foo (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  value integer
);
```
)

**Comment by martijndeh** [comment]
There are no plans to get the DDL side of Postgres supported right now.

There is a CLI available to set up your data model via migrations, see https://github.com/Ff00ff/mammoth-cli.
