### ISSUE TITLE
Maintainers

### ISSUE THREAD

**Issue by AuspeXeu** [Ff00ff/mammoth#279]
Just wondering, since I really like using mammoth in my projects, which also go into production, what your thoughts on maintainers are. It seems like you yourself don't have plenty of time to keep an eye on this library. Would it be worth adding some other maintainers to the repository to make sure there's someone available? Otherwise I feel like the library might just die due to a lack of support. Let me know your thoughts.

**Comment by martijndeh** [comment]
If someone is available to help and maintain mammoth: do let me know. I just gave @cakoose access.

When a change hits the master branch, and there is a version change, an update gets published to npm.

I'm planning to pick up some of the open issues the coming months as well.

**Comment by AuspeXeu** [comment]
I'd also be happy to help keeping the project alive :)
