### ISSUE TITLE
Star select no longer working

### ISSUE THREAD

**Issue by AuspeXeu** [Ff00ff/mammoth#282]
I just upgraded to the latest version and selecting using `star()` seems to be broken.

`db.select(star()).from(db.sites)`

Gives me a compiler error.
`Argument of type 'Star' is not assignable to parameter of type 'Selectable'`

**Comment by martijndeh** [comment]
I couldn’t reproduce this yet. I’ll try again later by using the npm build. Sometimes that gives different results, which I assume is happening here. Or is there a check (type unit test) missing you think?

**Comment by martijndeh** [comment]
Can you create a reproducible project in the below sandbox please? I tried to do it but a simple case doesn't seem to trigger any issues where `Star` is not assignable to parameter of type Selectable.  But maybe there is a specific table or query setup which only triggers this error?

https://codesandbox.io/s/focused-brook-9r8j3?file=/src/index.ts

For now I'm closing this one, but I'm happy to get this one fixed if we can create a reproducible sandbox.
