### ISSUE TITLE
select where not like

### ISSUE THREAD

**Issue by AuspeXeu** [Ff00ff/mammoth#333]
Is there a way to negate the like/ilike operator?

`select * from table where name is not like 'bob%';`

**Comment by martijndeh** [comment]
Would something like this work? 

`db.select(star()).from(db.table).where(not(db.table.name.like('bob%'));

**Comment by AuspeXeu** [comment]
Either that or just a `notLike` operator like we have it for `notIn` which I would actually prefer.

**Comment by AuspeXeu** [comment]
Created a PR for this #383
