### ISSUE TITLE
groupBy alias

### ISSUE THREAD

**Issue by AuspeXeu** [Ff00ff/mammoth#381]
I am getting a bit confused as to how to implement the following.

```
SELECT user.id, max(highscore.amount) AS best
FROM user RIGHT JOIN highscore
ON user.id = highscore.user_id
GROUP BY user.id
ORDER BY best DESC
```

What's the equivalent in mammoth notation?

```
db.select(db.user.id, max(db.highscore.amount).as('best'))
.from(db.user)
.rightJoin(db.highscore)
.on(db.user.id.eq(db.highscore.userId))
.groupBy(db.user.id)
.orderBy(????????)
```

**Comment by martijndeh** [comment]
I think something like the below makes sense. Does that work already? What do you think?

```ts
const best = max(db.highscore.amount).as('best');
const rows = await db.select(db.user.id, best)
  .from(db.user)
  .rightJoin(db.highscore).on(db.user.id.eq(db.highscore.userId))
  .groupBy(db.user.id)
  .orderBy(best);
```

**Comment by AuspeXeu** [comment]
This makes sense, yes. However, the generated SQL seems less ideal to me. The code you posted gives me this SQL.
```
SELECT user.id, max(highscore.amount) best
FROM user RIGHT JOIN highscore
ON user.id = highscore.user_id
GROUP BY user.id
ORDER BY max(highscore.amount) DESC
```

Shouldn't we simply use the alias in the `ORDER BY` statement?

**Comment by martijndeh** [comment]
This is also fixed now.

**Comment by AuspeXeu** [comment]
Any chance you could point me to the commit that fixes this? :)

**Comment by martijndeh** [comment]
Apologies. I pushed my changes and closed my laptop last night, assuming everything went through. 😅 But somehow it didn't. I just pushed the changes through.

**Comment by AuspeXeu** [comment]
Sorry if I am being picky about this one. Shouldn't this test actually fail, as the expected SQL string is missing the double quoted alias introduced yesterday?

https://github.com/Ff00ff/mammoth/commit/70e416c83cd7df94c3a4842f77a86c2e66c182ad#diff-dd39016209173bf6d19ea09508619f69e7ef43cb41d53156f395fafae8514100R466

**Comment by martijndeh** [comment]
Not a problem. It’s a good thing to ask questions.

No, because the implementation only quotes camelCase and reserved keywords. See the second test which does quote the expression alias.
