### ISSUE TITLE
Alias coalesce column

### ISSUE THREAD

**Issue by AuspeXeu** [Ff00ff/mammoth#382]
The following code
```
db.select(db.users.id, coalesce(max(db.results.timestamp), db.users.created).as('timestamp'))
  .from(db.users)
  .rightJoin(db.results)
  .on(db.user.id.eq(db.results.userId))
```
yields this invalid SQL statement
```
SELECT users.id, coalesce (MAX (results.timestamp), user.created) timestamp
FROM users
RIGHT JOIN results
ON (users.id = results.user_id)
```

Like you can see, there is an `AS` missing.

Edit: This seems to be the case for other helper functions as well. After dropping the `coalesce` function like this.
```
[...] max(db.results.timestamp) [...]
```
I still get the following SQL statement
```
[...] MAX (results.timestamp) timestamp [...]
```
Which also misses the `AS` keyword.

**Comment by martijndeh** [comment]
I believe the `AS` keyword is optional, so it's not something Mammoth is adding. What is the error you're getting?

**Comment by AuspeXeu** [comment]
Well. That there is a Syntax error and when I add `AS` I don't :)

**Comment by AuspeXeu** [comment]
So you're actually right that the `AS` is optional. However, we have the issue of missing double quotes here again. Since the column alias is called `timestamp` it has to be aliased to `"timestamp"`. So the `.as` methods should probably set double quotes?

**Comment by martijndeh** [comment]
A fix just landed in master.
