### ISSUE TITLE
Support pg & pool connections in createDatabase

### ISSUE THREAD

**Issue by moltar** [Ff00ff/mammoth#40]
# Problem

Sometimes a connection needs to be shared with other services in the application.

And `mammoth` allows passing only `databaseUrl` option and establishes own connection.

# Solution

Allow BYOD (Bring Your Own Database) connection to be passed.

**Comment by martijndeh** [comment]
This makes sense. Will you be planning to work on this yourself?

**Comment by moltar** [comment]
Unlikely will be working on this. I am not using `mammoth`. Was just checking it out & playing and noticed this.

TypeORM also suffers from the same issue, that is why it immediately stood out :)

**Comment by martijndeh** [comment]
Mammoth is now no longer including a database driver, so this issue is sort of resolved.
