### ISSUE TITLE
Automatically resolving schema and relationships directly from the database

### ISSUE THREAD

**Issue by ansarizafar** [Ff00ff/mammoth#402]
The title says it all Why create table definitions manually why not automatically resolving schema and relationships directly from the database.

**Comment by curwen** [comment]
There are many disadvantages to type generation over inference, such as ensuring consistency of the schema and types. I believe that type inference is one of Mammoth's defining features. Zapatos is a popular alternative that uses type generation (connects to DB). @martijndeh Might have more to add on the matter?

**Comment by martijndeh** [comment]
Yea so there is a plan to create something like `mammoth generate` which takes SQL as input and generates the Mammoth tables etc. But this is more of a one-time-thing to make it easier to start using Mammoth on an existing schema.

The downside of `mammoth generate` will be that it requires a build step. Of course you can run it using a watch of some sort. But the goal of Mammoth is to infer the types without a build step. If you don't mind a build step you should look into different libraries like [Zapatos](https://github.com/jawj/zapatos) which @curwen mentions.
