### ISSUE TITLE
Multicolumn indexes?

### ISSUE THREAD

**Issue by gilbert** [Ff00ff/mammoth#5]
Have you considered how to do indexes for multiple columns? I don't need them now but might in the future.

**Comment by martijndeh** [comment]
Not declaratively yet. I guess some special property or function should work which returns indices, but it shouldn’t collide with anything in user land so not too sure what the nicest solution is yet. Do you have any ideas?

Currently, to create multi-column indices, I simply generate a migration and add the sql to do it myself.
