### ISSUE TITLE
Optional columns when inserting

### ISSUE THREAD

**Issue by gilbert** [Ff00ff/mammoth#6]
I noticed nullable columns are still required to specify when inserting. For example:

```ts
export class Test {
  id = new UuidColumn().primaryKey().notNull();
  name = new TextColumn();
  createdAt = new TimestampWithTimeZoneColumn().notNull().default(new Now());
}
// ...
db.insertInto(db.test).values({
  name: null,
  createdAt: null,
})
```

here `name: null` is required even though it's nullable and `createdAt: null` is required even though it has a default.

Is this a limitation that you ran into? Or just haven't gotten around to making them optional in JS-land too? I can write a PR if it's possible.

**Comment by martijndeh** [comment]
Nowadays it’s possible to omit some types, that’s how the id property is excluded. But it’s hardcoded now so not really elegant.

It might be possible today to omit nullable and not null with defaults but I haven’t investigated further. I agree it would be nice if those nullable or default values may be omitted! So if you have time would be nice to understand if and how we can fix this! :)

**Comment by gilbert** [comment]
I have some questions about the code base. What's a good way to contact you? Perhaps https://gitter.im?

**Comment by martijndeh** [comment]
I’m working on something which solves this.

**Comment by martijndeh** [comment]
The changes are available in [mammoth@next](https://github.com/Ff00ff/mammoth/tree/next). Still needs some work to get the new set up in shape.

**Comment by gilbert** [comment]
Looks great so far! Super exciting.

**Comment by martijndeh** [comment]
Tests are passing again. I'll close this now as I consider this resolved. I'll try to get a release ready in the next few days. There is still some work left on the cli and the generator.
