### ISSUE TITLE
PG < 8.0.3 incompatible with Node 14

### ISSUE THREAD

**Issue by RXminuS** [Ff00ff/mammoth#77]
Just took me hours to figure this out...but PG < 8.0.3 is incompatible with Node 14. It doesn't crash, no errors, no stack traces...but when calling query the runtime just stops. I saw you're already using dependabot which opened a PR and I've verified that all tests pass when upgrading.

But just thought I'd post the problem here in case someone else is baffled. Could you merge in the newest deps and then this issue can be closed.

**Comment by martijndeh** [comment]
Thanks for mentioning! Closing this now as the database driver is gone from this library.
