### ISSUE TITLE
Can Mammoth be used with PostGis for spatial queries and how?

### ISSUE THREAD

**Issue by sixman9** [Ff00ff/mammoth#83]
**Is Mammoth suitable for PostGis spatial queries?**

Apologies, I'm neither a TypeScript nor PostGres expert but, I'd like to use both in a cloud project I'm starting.

I come from Java and a little C#, so I'd be thankful for strongly-typed queries.

**Comment by martijndeh** [comment]
No, not yet. But it sounds like a good first issue for someone to pick up. Do you have some specific queries in mind?
